// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njewrkkkykhsccvlwezg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qZXdya2treWtoc2Njdmx3ZXpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3ODcwMDMsImV4cCI6MjA2MDM2MzAwM30.y-4TVt2TwcXT68M9CWAfqqmI5yEayopME1AITK6S470";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);